---
version: 2
updates:
  - package-ecosystem: pip
    directory: /.config/
    schedule:
      day: sunday
      interval: weekly
    labels: []
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels: []
