dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - python-common
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
enabled: true
useGitignore: true
ignorePaths:
  - cspell.config.yaml
  - uv.lock
  - "*.egg-info"
  - src/tox_ansible/_version.py
  - pyproject.toml
  - .config/dictionary.txt
  - site
  - _readthedocs
  - coverage.lcov
languageSettings:
  - languageId: python
    allowCompoundWords: false
