#!/usr/bin/env python3
"""Generate .sdlc/adrs/README.md from ADR file metadata.

Parses each ADR-*.md for title, status, and date, then writes a
grouped-by-status index.  Intended to run as a pre-commit hook so the
README never drifts from the source ADR files.
"""

from __future__ import annotations

import re
import sys

from pathlib import Path


ADR_DIR = Path(__file__).resolve().parent.parent / ".sdlc" / "adrs"
README = ADR_DIR / "README.md"
ADR_PATTERN = re.compile(r"^ADR-(\d+)-(.+)\.md$")

STATUS_ORDER = [
    "Implemented",
    "Accepted",
    "Proposed",
    "Superseded",
]

_STATUS_DESCRIPTIONS: dict[str, str] = {
    "Implemented": "Decisions that are fully reflected in the codebase.",
    "Accepted": "Decisions that have been accepted but are not yet fully implemented.",
    "Proposed": "Decisions under consideration — not yet accepted or implemented.",
    "Superseded": "Decisions replaced by newer ADRs.",
}


def _normalize_status(raw: str) -> str:
    """Map the free-text status line to a canonical bucket.

    Args:
        raw: Raw status string from the ADR file.

    Returns:
        Canonical status string.
    """
    low = raw.lower().strip()
    if "superseded" in low:
        return "Superseded"
    if "implemented" in low:
        return "Implemented"
    if "accepted" in low:
        return "Accepted"
    return "Proposed"


def _parse_adr(path: Path) -> dict[str, str] | None:
    """Extract number, title, status, and date from an ADR file.

    Args:
        path: Path to an ADR markdown file.

    Returns:
        Dict with parsed metadata, or None if filename doesn't match.
    """
    m = ADR_PATTERN.match(path.name)
    if not m:
        return None

    number = m.group(1)
    text = path.read_text(encoding="utf-8")

    title_match = re.search(r"^#\s+ADR-\d+:\s*(.+)$", text, re.MULTILINE)
    title = title_match.group(1).strip() if title_match else path.stem

    status_match = re.search(r"^##\s+Status\s*\n+(.+?)$", text, re.MULTILINE)
    raw_status = status_match.group(1).strip() if status_match else "Proposed"
    status = _normalize_status(raw_status)
    status_detail = raw_status if raw_status != status else ""

    date_match = re.search(r"^##\s+Date\s*\n+(.+?)$", text, re.MULTILINE)
    date = date_match.group(1).strip() if date_match else ""

    return {
        "number": number,
        "filename": path.name,
        "title": title,
        "status": status,
        "status_detail": status_detail,
        "date": date,
    }


def _render(adrs: list[dict[str, str]]) -> str:
    """Render the full README content.

    Args:
        adrs: List of parsed ADR metadata dicts.

    Returns:
        Complete README markdown string.
    """
    grouped: dict[str, list[dict[str, str]]] = {s: [] for s in STATUS_ORDER}
    for adr in adrs:
        grouped.setdefault(adr["status"], []).append(adr)

    lines: list[str] = [
        "# Architecture Decision Records",
        "",
        "This directory contains the Architecture Decision Records (ADRs) for tox-ansible.",
        "",
        "<!-- AUTO-GENERATED by scripts/generate_adr_index.py — do not edit manually -->",
        "",
    ]

    for status in STATUS_ORDER:
        items = grouped.get(status, [])
        if not items:
            continue

        lines.append(f"## {status}")
        lines.append("")
        lines.append(_STATUS_DESCRIPTIONS.get(status, ""))
        lines.append("")
        lines.append("| ADR | Title | Date |")
        lines.append("|-----|-------|------|")
        for a in sorted(items, key=lambda x: int(x["number"])):
            num = a["number"]
            detail = f" ({a['status_detail']})" if a["status_detail"] else ""
            lines.append(f"| [ADR-{num}]({a['filename']}) | {a['title']}{detail} | {a['date']} |")
        lines.append("")

    lines.extend(
        [
            "## Creating New ADRs",
            "",
            "1. Copy the template from `../templates/adr.md`",
            f"2. Use the next available number (currently ADR-{_next_number(adrs):03d})",
            "3. Include:",
            "   - Status (Proposed → Accepted → Implemented)",
            "   - Date",
            "   - Context",
            "   - Options Considered",
            "   - Decision",
            "   - Rationale",
            "   - Consequences (positive/negative)",
            "   - Implementation Notes",
            "   - Related Decisions",
            "",
        ]
    )

    return "\n".join(lines)


def _next_number(adrs: list[dict[str, str]]) -> int:
    return max(int(a["number"]) for a in adrs) + 1 if adrs else 1


def main() -> int:
    """Parse ADR files and regenerate the index README.

    Returns:
        0 if no changes, 1 if README was updated or no ADRs found.
    """
    adr_files = sorted(ADR_DIR.glob("ADR-*.md"))
    adrs = [a for f in adr_files if (a := _parse_adr(f)) is not None]

    if not adrs:
        sys.stderr.write("No ADR files found\n")
        return 1

    seen: dict[str, str] = {}
    for a in adrs:
        num = a["number"]
        if num in seen:
            sys.stderr.write(
                f"ERROR: Duplicate ADR number {num}: {seen[num]} and {a['filename']}\n",
            )
            return 1
        seen[num] = a["filename"]

    content = _render(adrs)
    existing = README.read_text(encoding="utf-8") if README.exists() else ""

    if content == existing:
        return 0

    README.write_text(content, encoding="utf-8")
    sys.stderr.write(f"Updated {README} ({len(adrs)} ADRs)\n")
    return 1  # non-zero signals pre-commit that file was modified


if __name__ == "__main__":
    raise SystemExit(main())
