name: tox-ansible

on:
  pull_request:
    branches:
      - main
      - "releases/**"
      - "stable/**"
  workflow_call:

jobs:
  tox-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tox-ansible, includes tox
        run: python -m pip install tox-ansible

      - name: Generate matrix
        id: generate-matrix
        run: |
          python -m tox --ansible --gh-matrix --conf tox-ansible.ini

    outputs:
      envlist: ${{ steps.generate-matrix.outputs.envlist }}

  test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(needs.tox-matrix.outputs.envlist) }}
    name: ${{ matrix.entry.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.entry.python }}

      - name: Install tox-ansible, includes tox
        run: python -m pip install tox-ansible

      - name: Run tox test
        run: python -m tox --ansible -e ${{ matrix.entry.name }} --conf tox-ansible.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_passed:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.test.result }}',
          ]) == {'success'}"
